export const jobData = [
  {
    id: 1,
    jobTitle: "Senior React Developer",
    department: "Engineering",
    location: "San Francisco, CA",
    status: "active",
    minSalary: "120,000",
    maxSalary: "150,000",
    jobDescription: "Develop and maintain React-based web applications.",
    requirements: "5+ years experience, React expertise",
    skillsTags: ["React", "JavaScript", "CSS"],
    applicants: 18,
    posted: "1 week ago",
  },
  {
    id: 2,
    jobTitle: "Frontend Developer",
    department: "Engineering",
    location: "New York, NY",
    status: "archived",
    minSalary: "90,000",
    maxSalary: "120,000",
    jobDescription: "Work on UI components and responsive design.",
    requirements: "3+ years experience, HTML/CSS/JS",
    skillsTags: ["JavaScript", "HTML", "CSS"],
    applicants: 12,
    posted: "2 weeks ago",
  },
  {
    id: 3,
    jobTitle: "Full Stack Engineer",
    department: "Engineering",
    location: "Austin, TX",
    status: "active",
    minSalary: "110,000",
    maxSalary: "140,000",
    jobDescription: "Build scalable web applications using React and Node.js.",
    requirements: "4+ years experience, Node.js, React",
    skillsTags: ["React", "Node.js", "MongoDB"],
    applicants: 25,
    posted: "3 days ago",
  },
  {
    id: 4,
    jobTitle: "UI/UX Designer",
    department: "Design",
    location: "Remote",
    status: "active",
    minSalary: "80,000",
    maxSalary: "110,000",
    jobDescription: "Design user-friendly interfaces and prototypes.",
    requirements: "3+ years experience, Figma/AdobeXD",
    skillsTags: ["Figma", "Adobe XD", "Design Thinking"],
    applicants: 14,
    posted: "5 days ago",
  },
  {
    id: 5,
    jobTitle: "Backend Developer",
    department: "Engineering",
    location: "Seattle, WA",
    status: "archived",
    minSalary: "100,000",
    maxSalary: "130,000",
    jobDescription: "Develop and maintain backend APIs and databases.",
    requirements: "4+ years experience, Node.js, SQL",
    skillsTags: ["Node.js", "Express", "SQL"],
    applicants: 20,
    posted: "1 month ago",
  },
  {
    id: 6,
    jobTitle: "DevOps Engineer",
    department: "Engineering",
    location: "Boston, MA",
    status: "active",
    minSalary: "110,000",
    maxSalary: "140,000",
    jobDescription: "Manage CI/CD pipelines and cloud infrastructure.",
    requirements: "3+ years experience, AWS, Docker, Kubernetes",
    skillsTags: ["AWS", "Docker", "Kubernetes"],
    applicants: 10,
    posted: "2 weeks ago",
  },
  {
    id: 7,
    jobTitle: "Product Manager",
    department: "Product",
    location: "Chicago, IL",
    status: "archived",
    minSalary: "115,000",
    maxSalary: "145,000",
    jobDescription: "Lead product development and coordinate teams.",
    requirements: "5+ years experience, Agile, Scrum",
    skillsTags: ["Agile", "Scrum", "Roadmapping"],
    applicants: 8,
    posted: "3 weeks ago",
  },
  {
    id: 8,
    jobTitle: "QA Engineer",
    department: "Engineering",
    location: "Denver, CO",
    status: "active",
    minSalary: "85,000",
    maxSalary: "110,000",
    jobDescription: "Test software applications and report bugs.",
    requirements: "3+ years experience, Selenium, Jest",
    skillsTags: ["Selenium", "Jest", "Testing"],
    applicants: 16,
    posted: "1 week ago",
  },
  {
    id: 9,
    jobTitle: "Senior Node.js Developer",
    department: "Engineering",
    location: "Miami, FL",
    status: "active",
    minSalary: "120,000",
    maxSalary: "150,000",
    jobDescription: "Build scalable server-side applications.",
    requirements: "5+ years experience, Node.js, Express",
    skillsTags: ["Node.js", "Express", "MongoDB"],
    applicants: 22,
    posted: "2 days ago",
  },
  {
    id: 10,
    jobTitle: "Data Scientist",
    department: "Data",
    location: "San Francisco, CA",
    status: "archived",
    minSalary: "120,000",
    maxSalary: "160,000",
    jobDescription: "Analyze data and build predictive models.",
    requirements: "3+ years experience, Python, ML",
    skillsTags: ["Python", "Machine Learning", "Statistics"],
    applicants: 19,
    posted: "4 weeks ago",
  },
  {
    id: 11,
    jobTitle: "React Developer",
    department: "Engineering",
    location: "Remote",
    status: "active",
    minSalary: "100,000",
    maxSalary: "130,000",
    jobDescription: "Create dynamic React applications.",
    requirements: "3+ years experience, React, Redux",
    skillsTags: ["React", "Redux", "JavaScript"],
    applicants: 30,
    posted: "3 days ago",
  },
  {
    id: 12,
    jobTitle: "UX Researcher",
    department: "Design",
    location: "New York, NY",
    status: "active",
    minSalary: "90,000",
    maxSalary: "120,000",
    jobDescription: "Conduct user research and usability testing.",
    requirements: "3+ years experience, Research Methods",
    skillsTags: ["User Research", "UX", "Figma"],
    applicants: 7,
    posted: "1 week ago",
  },
  {
    id: 13,
    jobTitle: "Mobile App Developer",
    department: "Engineering",
    location: "Los Angeles, CA",
    status: "archived",
    minSalary: "100,000",
    maxSalary: "140,000",
    jobDescription: "Develop iOS and Android applications.",
    requirements: "3+ years experience, React Native/Swift/Kotlin",
    skillsTags: ["React Native", "Swift", "Kotlin"],
    applicants: 15,
    posted: "2 months ago",
  },
  {
    id: 14,
    jobTitle: "Technical Writer",
    department: "Product",
    location: "Remote",
    status: "active",
    minSalary: "70,000",
    maxSalary: "90,000",
    jobDescription: "Write documentation and user guides.",
    requirements: "2+ years experience, Technical Writing",
    skillsTags: ["Writing", "Documentation", "Confluence"],
    applicants: 9,
    posted: "5 days ago",
  },
  {
    id: 15,
    jobTitle: "Cloud Engineer",
    department: "Engineering",
    location: "Seattle, WA",
    status: "active",
    minSalary: "110,000",
    maxSalary: "140,000",
    jobDescription: "Manage cloud infrastructure and deployment.",
    requirements: "3+ years experience, AWS, Azure, GCP",
    skillsTags: ["AWS", "Azure", "GCP"],
    applicants: 13,
    posted: "1 week ago",
  },
  {
    id: 16,
    jobTitle: "Junior Frontend Developer",
    department: "Engineering",
    location: "Austin, TX",
    status: "archived",
    minSalary: "70,000",
    maxSalary: "90,000",
    jobDescription: "Assist in building frontend components.",
    requirements: "1+ years experience, React, HTML/CSS",
    skillsTags: ["React", "JavaScript", "HTML/CSS"],
    applicants: 11,
    posted: "3 weeks ago",
  },
  {
    id: 17,
    jobTitle: "Product Designer",
    department: "Design",
    location: "Chicago, IL",
    status: "active",
    minSalary: "95,000",
    maxSalary: "125,000",
    jobDescription: "Design product interfaces and prototypes.",
    requirements: "3+ years experience, Figma, Adobe XD",
    skillsTags: ["Figma", "Adobe XD", "UI Design"],
    applicants: 18,
    posted: "4 days ago",
  },
  {
    id: 18,
    jobTitle: "QA Automation Engineer",
    department: "Engineering",
    location: "Denver, CO",
    status: "active",
    minSalary: "90,000",
    maxSalary: "120,000",
    jobDescription: "Create automated test scripts for applications.",
    requirements: "3+ years experience, Selenium, Cypress",
    skillsTags: ["Selenium", "Cypress", "Automation"],
    applicants: 14,
    posted: "1 week ago",
  },
  {
    id: 19,
    jobTitle: "Senior Backend Developer",
    department: "Engineering",
    location: "Miami, FL",
    status: "archived",
    minSalary: "120,000",
    maxSalary: "150,000",
    jobDescription: "Develop backend services and APIs.",
    requirements: "5+ years experience, Node.js, SQL",
    skillsTags: ["Node.js", "Express", "PostgreSQL"],
    applicants: 20,
    posted: "1 month ago",
  },
  {
    id: 20,
    jobTitle: "Data Analyst",
    department: "Data",
    location: "Boston, MA",
    status: "active",
    minSalary: "80,000",
    maxSalary: "110,000",
    jobDescription: "Analyze data trends and generate reports.",
    requirements: "2+ years experience, Excel, SQL, Python",
    skillsTags: ["SQL", "Python", "Excel"],
    applicants: 17,
    posted: "3 days ago",
  },
  {
    id: 21,
    jobTitle: "React Native Developer",
    department: "Engineering",
    location: "Remote",
    status: "active",
    minSalary: "100,000",
    maxSalary: "130,000",
    jobDescription: "Develop cross-platform mobile applications.",
    requirements: "3+ years experience, React Native",
    skillsTags: ["React Native", "JavaScript", "Mobile"],
    applicants: 21,
    posted: "2 days ago",
  },
  {
    id: 22,
    jobTitle: "Scrum Master",
    department: "Product",
    location: "San Francisco, CA",
    status: "archived",
    minSalary: "110,000",
    maxSalary: "140,000",
    jobDescription: "Manage Agile teams and sprints.",
    requirements: "3+ years experience, Scrum Master Certification",
    skillsTags: ["Scrum", "Agile", "Leadership"],
    applicants: 6,
    posted: "2 months ago",
  },
  {
    id: 23,
    jobTitle: "Machine Learning Engineer",
    department: "Data",
    location: "New York, NY",
    status: "active",
    minSalary: "120,000",
    maxSalary: "160,000",
    jobDescription: "Develop ML models and AI solutions.",
    requirements: "3+ years experience, Python, ML, TensorFlow",
    skillsTags: ["Python", "Machine Learning", "TensorFlow"],
    applicants: 15,
    posted: "1 week ago",
  },
  {
    id: 24,
    jobTitle: "Frontend Engineer",
    department: "Engineering",
    location: "Los Angeles, CA",
    status: "active",
    minSalary: "95,000",
    maxSalary: "125,000",
    jobDescription: "Build responsive web applications.",
    requirements: "3+ years experience, React, Vue, Angular",
    skillsTags: ["React", "Vue", "Angular"],
    applicants: 23,
    posted: "4 days ago",
  },
  {
    id: 25,
    jobTitle: "Technical Support Engineer",
    department: "Support",
    location: "Remote",
    status: "archived",
    minSalary: "60,000",
    maxSalary: "80,000",
    jobDescription: "Provide technical support to clients and teams.",
    requirements: "1+ years experience, troubleshooting skills",
    skillsTags: ["Support", "Troubleshooting", "Customer Service"],
    applicants: 12,
    posted: "3 weeks ago",
  }
];